ALTER TABLE tasks ADD COLUMN IF NOT EXISTS nag_interval_minutes INTEGER DEFAULT NULL;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS nag_last_sent_at TIMESTAMPTZ DEFAULT NULL;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS nag_count INTEGER DEFAULT 0;
